In [6]:
import pandas as pd
import numpy as np
from pathlib import Path

print("Pandas version:", pd.__version__)
print("Numpy version:", np.__version__)

Pandas version: 3.0.6
Numpy version: 2.5.3

In [7]:
DATA_PATH = Path("../data/raw")

collisions = pd.read_csv(DATA_PATH / "collisions.csv")
vehicles = pd.read_csv(DATA_PATH / "vehicles.csv")
casualties = pd.read_csv(DATA_PATH / "casualties.csv")

C:\Users\shiva\AppData\Local\Temp\ipykernel_9284\3768706253.py:4: DtypeWarning: Columns (27: generic_make_model) have mixed types. Specify dtype option on import or set low_memory=False.
  vehicles = pd.read_csv(DATA_PATH / "vehicles.csv")

In [8]:
print("Collisions:", collisions.shape)
print("Vehicles:", vehicles.shape)
print("Casualties:", casualties.shape)

Collisions: (101525, 44)
Vehicles: (183948, 32)
Casualties: (127883, 24)

In [9]:
collisions.head()

,collision_index,collision_year,collision_ref_no,location_easting_osgr,location_northing_osgr,longitude,latitude,police_force,collision_severity,number_of_vehicles,...,carriageway_hazards_historic,carriageway_hazards,urban_or_rural_area,did_police_officer_attend_scene_of_accident,trunk_road_flag,lsoa_of_accident_location,enhanced_severity_collision,collision_injury_based,collision_adjusted_severity_serious,collision_adjusted_severity_slight
0,202517M101925,2025,17M101925,447673.0,519279.0,-1.26420,54.56650,17,3,1,...,-1,0,1,1,2,E01012014,3,1,0.0,1.0
1,202517L205225,2025,17L205225,454611.0,518597.0,-1.15704,54.55967,17,3,2,...,-1,0,1,1,2,E01012173,3,1,0.0,1.0
2,2025070971700,2025,070971700,354476.0,382656.0,-2.68516,53.33884,7,3,2,...,-1,0,2,1,2,E01012444,3,1,0.0,1.0
3,2025070403274,2025,070403274,361793.0,393163.0,-2.57655,53.43386,7,3,2,...,-1,0,2,3,2,E01012468,3,1,0.0,1.0
4,2025071000604,2025,071000604,366083.0,389327.0,-2.51157,53.39967,7,3,7,...,-1,0,2,1,1,E01012551,3,1,0.0,1.0

In [10]:
vehicles.head()

,collision_index,collision_year,collision_ref_no,vehicle_reference,vehicle_type,towing_and_articulation,vehicle_manoeuvre_historic,vehicle_manoeuvre,vehicle_direction_from,vehicle_direction_to,...,age_of_driver,age_band_of_driver,engine_capacity_cc,propulsion_code,age_of_vehicle,generic_make_model,driver_imd_decile,lsoa_of_driver,escooter_flag,driver_distance_banding
0,2025552501020,2025,552501020,2,2,0,-1,4,4,8,...,16,4,50,1,-1,MAKE AND MODEL REDACTED,10,E01020560,0,1
1,2025221557045,2025,221557045,1,2,0,-1,5,6,2,...,18,4,50,1,-1,MAKE AND MODEL REDACTED,2,E01013994,0,1
2,2025221551102,2025,221551102,2,2,0,-1,19,8,4,...,18,4,50,1,-1,MAKE AND MODEL REDACTED,4,E01035077,0,1
3,2025161606443,2025,161606443,1,2,0,-1,19,7,4,...,16,4,50,1,-1,MAKE AND MODEL REDACTED,7,E01012987,0,1
4,2025031672722,2025,031672722,2,9,0,-1,2,0,0,...,29,6,-1,3,-1,AUDI E-TRON,10,E01019251,0,1

In [11]:
casualties.head()

,collision_index,collision_year,collision_ref_no,vehicle_reference,casualty_reference,casualty_class,sex_of_casualty,age_of_casualty,age_band_of_casualty,casualty_severity,...,pedestrian_road_maintenance_worker,casualty_type,casualty_imd_decile,lsoa_of_casualty,enhanced_casualty_severity,casualty_injury_based,casualty_adjusted_severity_serious,casualty_adjusted_severity_slight,casualty_distance_banding,escooter_flag
0,2025010552583,2025,010552583,1,1,3,1,37,7,3,...,0,0,2,E01004311,-1,0,0.0,1.0,1,0
1,2025010554623,2025,010554623,1,1,3,1,13,3,3,...,0,0,4,E01003222,-1,0,0.0,1.0,1,0
2,2025010556322,2025,010556322,1,1,3,1,13,3,2,...,-1,0,9,E01034360,7,1,1.0,0.0,2,0
3,2025010558573,2025,010558573,1,1,3,1,68,10,2,...,-1,0,-1,-1,5,1,1.0,0.0,-1,0
4,2025010560329,2025,010560329,1,1,3,1,36,7,3,...,-1,0,6,E01004002,3,1,0.0,1.0,1,0

In [12]:
print("Collision columns")
for column in collisions.columns:
    print(column)

Collision columns
collision_index
collision_year
collision_ref_no
location_easting_osgr
location_northing_osgr
longitude
latitude
police_force
collision_severity
number_of_vehicles
number_of_casualties
date
day_of_week
time
local_authority_district
local_authority_ons_district
local_authority_highway
local_authority_highway_current
first_road_class
first_road_number
road_type
speed_limit
junction_detail_historic
junction_detail
junction_control
second_road_class
second_road_number
pedestrian_crossing_human_control_historic
pedestrian_crossing_physical_facilities_historic
pedestrian_crossing
light_conditions
weather_conditions
road_surface_conditions
special_conditions_at_site
carriageway_hazards_historic
carriageway_hazards
urban_or_rural_area
did_police_officer_attend_scene_of_accident
trunk_road_flag
lsoa_of_accident_location
enhanced_severity_collision
collision_injury_based
collision_adjusted_severity_serious
collision_adjusted_severity_slight

In [13]:
print("Vehicles columns")
for column in vehicles.columns:
    print(column)

Vehicles columns
collision_index
collision_year
collision_ref_no
vehicle_reference
vehicle_type
towing_and_articulation
vehicle_manoeuvre_historic
vehicle_manoeuvre
vehicle_direction_from
vehicle_direction_to
vehicle_location_restricted_lane_historic
vehicle_location_restricted_lane
junction_location
skidding_and_overturning
hit_object_in_carriageway
vehicle_leaving_carriageway
hit_object_off_carriageway
first_point_of_impact
vehicle_left_hand_drive
journey_purpose_of_driver_historic
journey_purpose_of_driver
sex_of_driver
age_of_driver
age_band_of_driver
engine_capacity_cc
propulsion_code
age_of_vehicle
generic_make_model
driver_imd_decile
lsoa_of_driver
escooter_flag
driver_distance_banding

In [14]:
print("Casualties columns")
for column in casualties.columns:
    print(column)

Casualties columns
collision_index
collision_year
collision_ref_no
vehicle_reference
casualty_reference
casualty_class
sex_of_casualty
age_of_casualty
age_band_of_casualty
casualty_severity
pedestrian_location
pedestrian_movement
car_passenger
bus_or_coach_passenger
pedestrian_road_maintenance_worker
casualty_type
casualty_imd_decile
lsoa_of_casualty
enhanced_casualty_severity
casualty_injury_based
casualty_adjusted_severity_serious
casualty_adjusted_severity_slight
casualty_distance_banding
escooter_flag

In [15]:
schema_summary = pd.DataFrame({
    "Dataset": ["Collisions", "Vehicles", "Casualties"],
    "Rows": [len(collisions), len(vehicles), len(casualties)],
    "Columns": [
        collisions.shape[1],
        vehicles.shape[1],
        casualties.shape[1]
    ]
})

schema_summary

      Dataset    Rows  Columns
0  Collisions  101525       44
1    Vehicles  183948       32
2  Casualties  127883       24

In [16]:
common_columns = set(collisions.columns) & set(vehicles.columns) & set(casualties.columns)

common_columns

{'collision_index', 'collision_ref_no', 'collision_year'}

In [17]:
print("COLLISIONS TABLE")

COLLISIONS TABLE

In [18]:
print("Total rows:", len(collisions))

Total rows: 101525

In [19]:
print("Unique collision_index:", collisions["collision_index"].nunique())

Unique collision_index: 101525

In [20]:
print("Duplicate collision_index:", collisions["collision_index"].duplicated().sum())

Duplicate collision_index: 0

In [21]:
print("Missing collision_index:", collisions["collision_index"].isna().sum())

Missing collision_index: 0

In [22]:
print("VEHICLES TABLE")
print("Total rows:", len(vehicles))
print("Unique collision_index:", vehicles["collision_index"].nunique())
print("Duplicate collision_index:", vehicles["collision_index"].duplicated().sum())
print("Missing collision_index:", vehicles["collision_index"].isna().sum())

print("\nCASUALTIES TABLE")
print("Total rows:", len(casualties))
print("Unique collision_index:", casualties["collision_index"].nunique())
print("Duplicate collision_index:", casualties["collision_index"].duplicated().sum())
print("Missing collision_index:", casualties["collision_index"].isna().sum())

VEHICLES TABLE
Total rows: 183948
Unique collision_index: 101525
Duplicate collision_index: 82423
Missing collision_index: 0

CASUALTIES TABLE
Total rows: 127883
Unique collision_index: 101525
Duplicate collision_index: 26358
Missing collision_index: 0

In [23]:
vehicle_orphans = ~vehicles["collision_index"].isin(collisions["collision_index"])
casualty_orphans = ~casualties["collision_index"].isin(collisions["collision_index"])

print("Vehicle records without matching collision:",
      vehicle_orphans.sum())

print("Casualty records without matching collision:",
      casualty_orphans.sum())

Vehicle records without matching collision: 0
Casualty records without matching collision: 0

In [24]:
def missing_report(df):
    report = pd.DataFrame({
        "missing_count": df.isnull().sum(),
        "missing_percent": (df.isnull().sum() / len(df) * 100).round(2)
    })

    return report[report["missing_count"] > 0].sort_values(
        "missing_percent",
        ascending=False
    )

print("COLLISIONS - MISSING VALUES")
display(missing_report(collisions))

print("\nVEHICLES - MISSING VALUES")
display(missing_report(vehicles))

print("\nCASUALTIES - MISSING VALUES")
display(missing_report(casualties))

COLLISIONS - MISSING VALUES

                        missing_count  missing_percent
location_easting_osgr               2              0.0
location_northing_osgr              2              0.0
longitude                           2              0.0
latitude                            2              0.0

VEHICLES - MISSING VALUES

Empty DataFrame
Columns: [missing_count, missing_percent]
Index: []

CASUALTIES - MISSING VALUES

Empty DataFrame
Columns: [missing_count, missing_percent]
Index: []

In [25]:
important_columns = [
    "collision_severity",
    "day_of_week",
    "road_type",
    "speed_limit",
    "junction_detail"
]

for column in important_columns:
    print(f"\n{column}")
    print(collisions[column].value_counts(dropna=False).sort_index())

collision_severity
collision_severity
1     1453
2    25191
3    74881
Name: count, dtype: int64

day_of_week
day_of_week
1    11197
2    14309
3    14880
4    15369
5    15304
6    16811
7    13655
Name: count, dtype: int64

road_type
road_type
1     6795
2     2398
3    14610
6    74150
7     1619
9     1953
Name: count, dtype: int64

speed_limit
speed_limit
20    20045
30    49673
40     8886
50     4612
60    12709
70     5600
Name: count, dtype: int64

junction_detail
junction_detail
-1      6701
 0     45333
 13    28198
 16     9456
 17     1504
 18     2144
 19     6762
 99     1427
Name: count, dtype: int64

In [26]:
for column in important_columns:
    values = sorted(collisions[column].dropna().unique())
    print(f"{column}: {values}")

collision_severity: [np.int64(1), np.int64(2), np.int64(3)]
day_of_week: [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7)]
road_type: [np.int64(1), np.int64(2), np.int64(3), np.int64(6), np.int64(7), np.int64(9)]
speed_limit: [np.int64(20), np.int64(30), np.int64(40), np.int64(50), np.int64(60), np.int64(70)]
junction_detail: [np.int64(-1), np.int64(0), np.int64(13), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(99)]

In [27]:
for column in important_columns:
    values = collisions[column].dropna().unique().tolist()
    print(f"{column}: {sorted(values)}")

collision_severity: [1, 2, 3]
day_of_week: [1, 2, 3, 4, 5, 6, 7]
road_type: [1, 2, 3, 6, 7, 9]
speed_limit: [20, 30, 40, 50, 60, 70]
junction_detail: [-1, 0, 13, 16, 17, 18, 19, 99]

In [28]:
severity_map = {
    # official mappings here
}

In [ ]:
# Profiling the date and time

In [29]:
print("Date data type:", collisions["date"].dtype)
print("Time data type:", collisions["time"].dtype)

print("\nFirst 10 dates:")
print(collisions["date"].head(10).tolist())

print("\nFirst 10 times:")
print(collisions["time"].head(10).tolist())

print("\nMissing dates:", collisions["date"].isna().sum())
print("Missing times:", collisions["time"].isna().sum())

Date data type: str
Time data type: str

First 10 dates:
['04/02/2025', '07/05/2025', '27/11/2025', '15/05/2025', '08/12/2025', '03/10/2025', '25/07/2025', '05/11/2025', '19/11/2025', '20/08/2025']

First 10 times:
['15:00', '09:35', '18:18', '16:30', '07:45', '12:11', '11:45', '17:31', '16:00', '16:40']

Missing dates: 0
Missing times: 0

In [30]:
print("Exact duplicate rows:")

print("Collisions:", collisions.duplicated().sum())
print("Vehicles:", vehicles.duplicated().sum())
print("Casualties:", casualties.duplicated().sum())

Exact duplicate rows:
Collisions: 0
Vehicles: 0
Casualties: 0

In [31]:
print("COLLISIONS DATA TYPES")
print(collisions.dtypes.value_counts())

print("\nVEHICLES DATA TYPES")
print(vehicles.dtypes.value_counts())

print("\nCASUALTIES DATA TYPES")
print(casualties.dtypes.value_counts())

COLLISIONS DATA TYPES
int64      30
str         8
float64     6
Name: count, dtype: int64

VEHICLES DATA TYPES
int64     28
str        3
object     1
Name: count, dtype: int64

CASUALTIES DATA TYPES
int64      19
str         3
float64     2
Name: count, dtype: int64

In [32]:
datasets = {
    "Collisions": collisions,
    "Vehicles": vehicles,
    "Casualties": casualties
}

for name, df in datasets.items():
    print(f"\n{name.upper()}")

    for dtype in ["str", "object", "float64"]:
        columns = df.select_dtypes(include=[dtype]).columns.tolist()
        print(f"{dtype}: {columns}")

COLLISIONS
str: ['collision_index', 'collision_ref_no', 'date', 'time', 'local_authority_ons_district', 'local_authority_highway', 'local_authority_highway_current', 'lsoa_of_accident_location']
object: ['collision_index', 'collision_ref_no', 'date', 'time', 'local_authority_ons_district', 'local_authority_highway', 'local_authority_highway_current', 'lsoa_of_accident_location']
float64: ['location_easting_osgr', 'location_northing_osgr', 'longitude', 'latitude', 'collision_adjusted_severity_serious', 'collision_adjusted_severity_slight']

VEHICLES
str: ['collision_index', 'collision_ref_no', 'lsoa_of_driver']
object: ['collision_index', 'collision_ref_no', 'generic_make_model', 'lsoa_of_driver']
float64: []

CASUALTIES
str: ['collision_index', 'collision_ref_no', 'lsoa_of_casualty']
object: ['collision_index', 'collision_ref_no', 'lsoa_of_casualty']
float64: ['casualty_adjusted_severity_serious', 'casualty_adjusted_severity_slight']

C:\Users\shiva\AppData\Local\Temp\ipykernel_9284\2877823728.py:11: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  columns = df.select_dtypes(include=[dtype]).columns.tolist()
C:\Users\shiva\AppData\Local\Temp\ipykernel_9284\2877823728.py:11: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  columns = df.select_dtypes(include=[dtype]).columns.tolist()
C:\Users\shiva\AppData\Local\Temp\ipykernel_9284\2877823728.py:11: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  columns = df.select_dtypes(include=[dtype]).columns.tolist()

In [33]:
for name, df in datasets.items():
    print(f"\n{name.upper()}")
    
    non_numeric = df.select_dtypes(exclude=["number"]).columns.tolist()
    float_columns = df.select_dtypes(include=["float64"]).columns.tolist()
    
    print("Non-numeric columns:", non_numeric)
    print("Float columns:", float_columns)

COLLISIONS
Non-numeric columns: ['collision_index', 'collision_ref_no', 'date', 'time', 'local_authority_ons_district', 'local_authority_highway', 'local_authority_highway_current', 'lsoa_of_accident_location']
Float columns: ['location_easting_osgr', 'location_northing_osgr', 'longitude', 'latitude', 'collision_adjusted_severity_serious', 'collision_adjusted_severity_slight']

VEHICLES
Non-numeric columns: ['collision_index', 'collision_ref_no', 'generic_make_model', 'lsoa_of_driver']
Float columns: []

CASUALTIES
Non-numeric columns: ['collision_index', 'collision_ref_no', 'lsoa_of_casualty']
Float columns: ['casualty_adjusted_severity_serious', 'casualty_adjusted_severity_slight']

In [34]:
checks = {
    "Collisions": {
        "number_of_vehicles": collisions["number_of_vehicles"],
        "number_of_casualties": collisions["number_of_casualties"],
        "speed_limit": collisions["speed_limit"]
    },
    "Vehicles": {
        "age_of_driver": vehicles["age_of_driver"]
    },
    "Casualties": {
        "age_of_casualty": casualties["age_of_casualty"]
    }
}

for dataset, columns in checks.items():
    print(f"\n{dataset.upper()}")

    for column, series in columns.items():
        print(
            f"{column}: "
            f"min={series.min()}, "
            f"max={series.max()}"
        )

COLLISIONS
number_of_vehicles: min=1, max=17
number_of_casualties: min=1, max=142
speed_limit: min=20, max=70

VEHICLES
age_of_driver: min=-1, max=105

CASUALTIES
age_of_casualty: min=-1, max=105